version: "3"
services:
  vcr-agent3:
    build:
      context: .
      dockerfile: agent/Dockerfile.acapy
    ports:
      - 8012:8010
      - 8003:8001
    networks:
      - agent3-net    # Same external network as wallet-db
    entrypoint: /bin/bash
    command: [
        "-c",
        "sleep 5; \
        aca-py start \
        --auto-provision \
        --seed '00000000000o_digiy_3_wallet_seed' \
        --inbound-transport http '0.0.0.0' 8001 \
        --endpoint 'http://host.docker.internal:8003' \
        --outbound-transport http \
        --genesis-url 'http://test.bcovrin.vonx.io/genesis' \
        --auto-accept-invites \
        --auto-accept-requests \
        --auto-ping-connection \
        --auto-respond-messages \
        --auto-respond-credential-proposal \
        --auto-respond-credential-offer \
        --auto-respond-credential-request \
        --auto-store-credential \
        --auto-respond-presentation-proposal \
        --auto-respond-presentation-request \
        --auto-verify-presentation \
        --preserve-exchange-records \
        --wallet-type 'askar' \
        --wallet-name 'acapy_agent3_wallet' \
        --wallet-key 'key' \
        --wallet-storage-type 'postgres_storage' \
        --wallet-storage-config '{\"url\":\"wallet3-db:5432\",\"max_connections\":5}' \
        --wallet-storage-creds '{\"account\":\"DB_USER\",\"password\":\"DB_PASSWORD\",\"admin_account\":\"postgres\",\"admin_password\":\"mysecretpassword\"}' \
        --admin '0.0.0.0' 8010 \
        --admin-insecure-mode \
        --label 'tester_agent3.2' \
        --log-level 'debug' ",
      ]
    depends_on:
      - wallet3-db

networks:
  agent3-net:
    external: true  # Refer to the external network