version: "3"
services:
  wallet3-db:
    build: ./db
    environment:
      - POSTGRES_USER=DB_USER
      - POSTGRES_PASSWORD=DB_PASSWORD
      - POSTGRES_ADMIN_USER=postgres
      - POSTGRES_ADMIN_PASSWORD=mysecretpassword
    networks:
      - agent3-net     # Use an external network that will be shared with agent3 service
    ports:
      - 5434:5432  # Map external port 5434 to internal port 5432  
    volumes:
      - wallet3-db-data:/var/lib/postgresql/data
    expose:
      - "5432"  # Expose to internal network, not public

volumes:
  wallet3-db-data:

networks:
  agent3-net:
    driver: bridge  # This will link to the network in the other file
    name: agent3-net